### ISSUE TITLE
hello,can you add the code of generating result.csv in your predict.py?if not ,that evaluation will not pass.

### ISSUE THREAD

**Issue by JXQI** [M3DV/FracNet#2]

**Comment by duducheng** [comment]
Sorry for this mistake, we will fix it soon.

**Comment by JXQI** [comment]
At the same time，I think your  main.py  can add the code of saving model  after training!

example:
               torch.save(model.state_dict(),"./models/3dUnet.pth")

then,in predict.py :
              "model = nn.DataParallel(model).cuda()" should follow the "model = UNet(1, 1, n=16)" 
do like this ,the code will not Interrupt！ just suggest!

**Comment by kaimingkuang** [comment]
New commits pushed. Now predict.py generates .nii and .csv files in alignment with the RibFrac challenge requirements.
