### ISSUE TITLE
Some dimensions of the generated forecast file are incorrect？for example,RibFrac421-label.nii.gz should (512,512,325),but get a shape (512,512,345)

### ISSUE THREAD

**Issue by JXQI** [M3DV/FracNet#3]

**Comment by JXQI** [comment]
I think should add the code after image_path_list:

indice=[i.split('/')[-1].split('-')[0] for i in image_path_list]
image_path_list=[index for _,index in sorted(zip(indice,image_path_list))]

**Comment by kaimingkuang** [comment]
> I think should add the code after image_path_list:
> 
> indice=[i.split('/')[-1].split('-')[0] for i in image_path_list]
> image_path_list=[index for _,index in sorted(zip(indice,image_path_list))]

Fixed with pull request #4
