### ISSUE TITLE
Possible bug in _predict_single_image

### ISSUE THREAD

**Issue by junayednaushad** [M3DV/FracNet#5]
Hi, I think there might be a bug in `predict.py` specifically the `_predict_single_image` function because I have followed the instructions on the README but all of my predictions are just 0s. On line 72 `pred` is set to 0, then on line 82 `cur_pred_patch` is set to `pred` so `cur_pred_patch` is just 0 and therefore the condition on line 91 never becomes true.

**Comment by kaimingkuang** [comment]
> Hi, I think there might be a bug in `predict.py` specifically the `_predict_single_image` function because I have followed the instructions on the README but all of my predictions are just 0s. On line 72 `pred` is set to 0, then on line 82 `cur_pred_patch` is set to `pred` so `cur_pred_patch` is just 0 and therefore the condition on line 91 never becomes true.

Thanks for spotting this bug. It should be `output[i]` at the else part of `np.where`. New commits have been pushed and it should be fixed now.
